production:
  SLACK_API_TOKEN: xoxb-70676684256-fvwGjiL7zVJEpDSv61xilmNH
  POSTGRES_DB_HOST: 127.0.0.1
  POSTGRES_DB_NAME: slack_bot
  POSTGRES_DB_USER: postgres
  POSTGRES_DB_PASSWORD: root  
  POSTGRES_DB_SU_USER: root
  POSTGRES_DB_SU_PASSWORD: root
  REDIS_HOST: localhost
  REDIS_PORT: '6379'
development:
  SLACK_API_TOKEN: xoxb-70676684256-fvwGjiL7zVJEpDSv61xilmNH
  POSTGRES_DB_HOST: localhost
  POSTGRES_DB_NAME: slack_bot
  POSTGRES_DB_USER: root
  POSTGRES_DB_PASSWORD: root
  POSTGRES_DB_SU_USER: root
  POSTGRES_DB_SU_PASSWORD: root
  REDIS_HOST: localhost
  REDIS_PORT: '6379'

  # sudo /etc/init.d/postgresql start 
  # sudo -i -u test1